/*
 * Creates T-SQL code that detaches all non-system databases from the 
 * server. This script doens't actually detach the database, but instead 
 * creates T-SQL code that detaches the databases.
 * 
 * Best to output the query resutls to text or to a file instead of a table 
 * so it formats the commands properly.
 * 
 * If you want to later reattach the database files using code generated by 
 * Attach All Databases.sql, you must run that that script before running the 
 * code generated by this script.
 *
 * Dan Smith: 2017-08-23
 */

 -- Don't need the row count at the end of the script.
 set nocount on
 go

select --db.[name] as [Name], df.physical_name as [DataFile], lf.physical_name as [LogFile], replace(lf.physical_name, '\Data\', '\Log\') as [NewLogFile],
replace(N'
ALTER DATABASE [$0] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
EXEC master.dbo.sp_detach_db @dbname = N''$0'', @skipchecks = ''false''
GO
', '$0', db.[Name]) 
from sys.databases as db
inner join sys.master_files df
	on df.database_id = db.database_id and df.[type] = 0
inner join sys.master_files lf
	on lf.database_id = db.database_id and lf.[type] = 1
where db.[name] not in ('master','model','msdb','tempdb')
order by db.[name]